### ISSUE TITLE
White and blue artifacts

### ISSUE THREAD

**Issue by dingyifei** [flowdriveai/flowpilot#5] opened 2022-10-17 20:11 UTC
Pixel 6A

Android 12

Tnn-model

Symptom: blue horizontal lines(multiple pixel) and white triangular geometry occasionally show up.

**Comment by MankaranSingh** [comment] 2022-10-18 02:57
The white triangle is lead car detection. Its a feature not a bug. 
Need to look at blue glitch. Its probably something wrong with path visualisation.

**Comment by MankaranSingh** [comment] 2022-11-06 04:24
Seems to ve fixed in master branch. High CPU usage can also cause this artifact sometimes.

**Closed by MankaranSingh** 2022-11-06 04:24 UTC
